DROP SCHEMA video_games CASCADE;
CREATE SCHEMA video_games;

DROP TABLE IF EXISTS video_games.genre;

CREATE TABLE video_games.genre (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  genre_name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);




DROP TABLE IF EXISTS video_games.publisher;

CREATE TABLE video_games.publisher (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  publisher_name VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
);




DROP TABLE IF EXISTS video_games.region;

CREATE TABLE video_games.region (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  region_name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);




DROP TABLE IF EXISTS video_games.platform;

CREATE TABLE video_games.platform (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  platform_name VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (id)
);


COMMIT;

DROP TABLE IF EXISTS video_games.game;

CREATE TABLE video_games.game (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  genre_id INT DEFAULT NULL,
  game_name VARCHAR(200) DEFAULT NULL,
  CONSTRAINT pk_game PRIMARY KEY (id),
  CONSTRAINT fk_gm_gen FOREIGN KEY (genre_id) REFERENCES video_games.genre (id)
);




COMMIT;
DROP TABLE IF EXISTS video_games.game_publisher;

CREATE TABLE video_games.game_publisher (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  game_id INT DEFAULT NULL,
  publisher_id INT DEFAULT NULL,
  CONSTRAINT pk_gamepub PRIMARY KEY (id),
  CONSTRAINT fk_gpu_gam FOREIGN KEY (game_id) REFERENCES video_games.game (id),
  CONSTRAINT fk_gpu_pub FOREIGN KEY (publisher_id) REFERENCES video_games.publisher (id)
);



COMMIT;
DROP TABLE IF EXISTS video_games.game_platform;

CREATE TABLE video_games.game_platform (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  game_publisher_id INT DEFAULT NULL,
  platform_id INT DEFAULT NULL,
  release_year INT DEFAULT NULL,
  CONSTRAINT pk_gameplatform PRIMARY KEY (id),
  CONSTRAINT fk_gpl_gp FOREIGN KEY (game_publisher_id) REFERENCES video_games.game_publisher (id),
  CONSTRAINT fk_gpl_pla FOREIGN KEY (platform_id) REFERENCES video_games.platform (id)
);




COMMIT;
DROP TABLE IF EXISTS video_games.region_sales;

CREATE TABLE video_games.region_sales (
  region_id INT DEFAULT NULL,
  game_platform_id INT DEFAULT NULL,
  num_sales DECIMAL(5,2) DEFAULT NULL,
  CONSTRAINT fk_rs_gp FOREIGN KEY (game_platform_id) REFERENCES video_games.game_platform (id),
  CONSTRAINT fk_rs_reg FOREIGN KEY (region_id) REFERENCES video_games.region (id)
);





COMMIT;
