"""Generate dbt project from modeling plan."""
from pathlib import Path
from jinja2 import Template
from schemalytics.models import Schema, ModelingPlan
from schemalytics import templates


def render(template_str: str, **kwargs) -> str:
    """Render a Jinja2 template."""
    escaped = template_str.replace("{{ config", "{% raw %}{{ config{% endraw %}")
    escaped = escaped.replace("{{ source", "{% raw %}{{ source{% endraw %}")
    escaped = escaped.replace("{{ ref", "{% raw %}{{ ref{% endraw %}")
    escaped = escaped.replace("{{ dbt_utils", "{% raw %}{{ dbt_utils{% endraw %}")
    escaped = escaped.replace(") }}", ") }}{% raw %}{% endraw %}")
    
    return Template(escaped).render(**kwargs)


def format_columns(columns: list[str], indent: int = 4) -> str:
    """Format column list with one column per line."""
    spaces = " " * indent
    return ",\n".join(f"{spaces}{col}" for col in columns)


def generate_dbt_project(
    schema: Schema,
    plan: ModelingPlan,
    output_dir: str,
    project_name: str = "schemalytics_project",
    source_schema: str = "public",
) -> Path:
    """Generate complete dbt project structure."""
    base = Path(output_dir)
    
    # Create directories
    dirs = [
        base,
        base / "models" / "bronze",
        base / "models" / "silver" / "dimensions",
        base / "models" / "silver" / "facts",
        base / "models" / "gold",
        base / "tests",
        base / "macros",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)
    
    # dbt_project.yml
    (base / "dbt_project.yml").write_text(
        render(templates.DBT_PROJECT_TEMPLATE, project_name=project_name)
    )
    
    # sources.yml
    (base / "models" / "sources.yml").write_text(
        render(templates.SOURCES_TEMPLATE, schema=source_schema, tables=plan.bronze)
    )
    
    # Bronze models
    for table in plan.bronze:
        sql = f"""-- Bronze: Raw passthrough from source
{{{{ config(materialized='view') }}}}

select *
from {{{{ source('raw', '{table}') }}}}
"""
        (base / "models" / "bronze" / f"bronze_{table}.sql").write_text(sql)
    
    # Dimension models
    for dim in plan.dimensions:
        if dim.scd_type == 1:
            cols = format_columns(dim.columns)
            sql = f"""-- Dimension: {dim.name} (SCD Type 1)
{{{{ config(materialized='table') }}}}

select
{cols}
from {{{{ ref('bronze_{dim.source_table}') }}}}
"""
        else:
            pk = dim.columns[0] if dim.columns else "id"
            cols = format_columns(dim.columns)
            sql = f"""-- Dimension: {dim.name} (SCD Type 2)
{{{{ config(materialized='table') }}}}

select
    {{{{ dbt_utils.generate_surrogate_key(['{pk}']) }}}} as {dim.name}_sk,
{cols},
    current_timestamp as valid_from,
    null::timestamp as valid_to,
    true as is_current
from {{{{ ref('bronze_{dim.source_table}') }}}}
"""
        (base / "models" / "silver" / "dimensions" / f"{dim.name}.sql").write_text(sql)
    
    # Fact models
    for fact in plan.facts:
        pk = fact.dimension_keys[0] if fact.dimension_keys else "id"
        all_cols = fact.dimension_keys + [fact.date_column] + fact.measures
        cols = format_columns(all_cols)
        sql = f"""-- Fact: {fact.name}
{{{{ config(materialized='table') }}}}

select
    {{{{ dbt_utils.generate_surrogate_key(['{pk}']) }}}} as {fact.name}_sk,
{cols}
from {{{{ ref('bronze_{fact.source_table}') }}}}
"""
        (base / "models" / "silver" / "facts" / f"{fact.name}.sql").write_text(sql)
    
    # README
    readme = f"""# {project_name}

Generated by Schemalytics.

## Structure
- **bronze/**: Raw passthrough from source ({len(plan.bronze)} models)
- **silver/dimensions/**: Dimensional models ({len(plan.dimensions)} models)
- **silver/facts/**: Fact tables ({len(plan.facts)} models)
- **gold/**: Aggregates (TODO)

## Models
### Dimensions
{chr(10).join(f'- {d.name}: {d.grain}' for d in plan.dimensions)}

### Facts
{chr(10).join(f'- {f.name}: {f.grain}' for f in plan.facts)}
"""
    (base / "README.md").write_text(readme)
    
    return base
