version: 2

sources:
  - name: raw
    schema: public
    tables:
      
      - name: territories
      
      - name: order_details
      
      - name: employee_territories
      
      - name: us_states
      
      - name: customers
      
      - name: orders
      
      - name: employees
      
      - name: shippers
      
      - name: products
      
      - name: categories
      
      - name: suppliers
      
      - name: region
      
      - name: customer_demographics
      
      - name: customer_customer_demo
      